version: "3.7"

services:

  # app:
  #   image: sample.ml.app
  #   volumes:
  #     - ./samples/app:/opt/app
  #     - ./samples/app/.data:/opt/data
  #     - ./:/opt/root
  #   build:
  #     context: ./samples/app
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 7888:7888
  #   # command: bash c dev
  #   command: tail -f /dev/null
  #   stdin_open: true
  #   tty: true
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '4'
  #         memory: 4096M

  # tln:
  #   image: sample.ml.tln
  #   volumes:
  #     - ./samples/tln:/opt/app
  #     - ./samples/tln/.data:/opt/data
  #     - ./:/opt/root
  #   build:
  #     context: ./samples/tln
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 7888:7888
  #   # command: bash c dev
  #   command: tail -f /dev/null
  #   stdin_open: true
  #   tty: true
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '4'
  #         memory: 4096M

  mxnet:
    image: sample.ml.mxnet
    volumes:
      - ./mxnet:/opt/app
      - ./mxnet/.data:/opt/data
      - ./:/opt/root
    build:
      context: ./mxnet
      dockerfile: ./Dockerfile
    ports:
      - 7888:7888
    # command: bash c dev
    command: tail -f /dev/null
    environment:
      - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8192M